name: ner
channels:
  - conda-forge
dependencies:
  - python=3.8.8
  - pip==20.2.3
  - pip:
    - spacy==3.0.6
    - fastapi==0.63.0
    - uvicorn
    - python-multipart==0.0.5
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz
    - SQLAlchemy==1.3.22
    - alembic==1.4.3
    - psycopg2-binary==2.8.6
