version: '3.8'
services:

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spacy_ner
    ports:
      - 5432:5432

  server:
    build: .
    command: uvicorn src.app_ner:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
